### ISSUE TITLE
Component Getting invisible

### ISSUE THREAD

**Issue by nishantpardamwar** [toystars/react-native-multiple-select#11]
Using 
"react-native-multiple-select": "^0.2.1",
"react-native-vector-icons": "^4.2.0",

everything is working fine except when item is selected and submit is clicked, whole MultiSelect component gets invisible instead of showing selected items.

**Comment by toystars** [comment]
@nishantpardamwar can you paste a snippet of your code here? So I'll create a brand new RN project and try to reproduce.

**Comment by nishantpardamwar** [comment]
index.android.js

`import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import MultiSelect from 'react-native-multiple-select';
const items = [{
  id: '92iijs7yta',
  name: 'Ondo',
}, {
  id: 'a0s0a8ssbsd',
  name: 'C2G',
}, {
  id: '16hbajsabsd',
  name: 'Calabar',
}, {
  id: 'nahs75a5sg',
  name: 'Fourth Item',
}, {
  id: '667atsas',
  name: 'Fifth Item',
}];

export default class Multi extends Component {
  selectedItem(selectedItems){
      // do something with selectedItems
      this.setState({sItems : selectedItems})
      console.log(selectedItems);
  }

  render(){
    return(
      <View style={{margin:16}}>
        <MultiSelect
          items={items}
          uniqueKey="id"
          selectedItemsChange={(selectedItem)=>{
            this.selectedItem(selectedItem)
          }}
          selectedItems={[]}
          selectText="Pick Items"
          searchInputPlaceholderText="Search Items..."
        />
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('Multi', () => Multi);
`

package.json

`{
  "name": "Multi",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.1.4",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.2",
    "react-native-multiple-select": "^0.2.1",
    "react-native-vector-icons": "^4.2.0",
    "underscore": "^1.8.3"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "1.9.2",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by toystars** [comment]
For some weird reasons, adding `flex`to the topmost `View` fixed it. I'll investigate further and push a permanent fix

index.android.js

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import MultiSelect from 'react-native-multiple-select';
const items = [{
  id: '92iijs7yta',
  name: 'Ondo',
}, {
  id: 'a0s0a8ssbsd',
  name: 'C2G',
}, {
  id: '16hbajsabsd',
  name: 'Calabar',
}, {
  id: 'nahs75a5sg',
  name: 'Fourth Item',
}, {
  id: '667atsas',
  name: 'Fifth Item',
}];

export default class Multi extends Component {
  selectedItem(selectedItems){
      // do something with selectedItems
      this.setState({sItems : selectedItems})
      console.log(selectedItems);
  }

  render(){
    return(
      <View style={{ flex: 1, margin:16 }}>
        <MultiSelect
          items={items}
          uniqueKey="id"
          selectedItemsChange={(selectedItem)=>{
            this.selectedItem(selectedItem)
          }}
          selectedItems={[]}
          selectText="Pick Items"
          searchInputPlaceholderText="Search Items..."
        />
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('Multi', () => Multi);
```

package.json
```
{
  "name": "Multi",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "native-base": "^2.1.4",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.2",
    "react-native-multiple-select": "^0.2.1",
    "react-native-vector-icons": "^4.2.0",
    "underscore": "^1.8.3"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "1.9.2",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by Adar-Li** [comment]
@toystars hi,i encountered such a problem.
![screenshot_20170605-164122](https://cloud.githubusercontent.com/assets/13981812/26777365/7f204cc2-4a0f-11e7-96d0-bd270bbbf9ed.png)
index.js
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import MultiSelect from 'react-native-multiple-select';

const items = [{
  id: '92iijs7yta',
  name: 'Ondo',
}, {
  id: 'a0s0a8ssbsd',
  name: 'C2G',
}, {
  id: '16hbajsabsd',
  name: 'Calabar',
}, {
  id: 'nahs75a5sg',
  name: 'Fourth Item',
}, {
  id: '667atsas',
  name: 'Fifth Item',
}];

export default class Multi extends Component {
  selectedItem(selectedItems){
      // do something with selectedItems
      this.setState({sItems : selectedItems})
      console.log(selectedItems);
  }

  render(){
    return(
      <View style={{ flex: 1, margin:16 }}>
        <MultiSelect
          items={items}
          uniqueKey="id"
          selectedItemsChange={(selectedItem)=>{
            this.selectedItem(selectedItem)
          }}
          selectedItems={[]}
          selectText="Pick Items"
          searchInputPlaceholderText="Search Items..."
        />
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

package.json
{
  "name": "example",
  "version": "0.3.0",
  "private": true,
  "scripts": {
    "configureJPush": "node node_modules/jpush-react-native/JPushConfiguration.js",
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "ac-qrcode": "^1.0.1",
    "native-base": "^2.1.4",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.1",
    "react-native-audio": "^3.2.2",
    "react-native-beautiful-video-recorder": "^1.2.0",
    "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
    "react-native-drawer": "^2.3.0",
    "react-native-image-crop-picker": "^0.13.0",
    "react-native-image-picker": "^0.26.3",
    "react-native-modal-dropdown": "^0.4.2",
    "react-native-multiple-select": "^0.2.1",
    "react-native-snap-carousel": "2.1.1",
    "react-native-sound": "^0.10.1",
    "react-native-vector-icons": "^4.0.1",
    "react-native-video": "^1.0.0",
    "underscore": "^1.8.3"
  },
  "devDependencies": {
    "babel-preset-react-native": "1.9.1"
  }
}

**Comment by nishantpardamwar** [comment]
@toystars 
thanks for the reply, my issue is resolved by adding flex.

**Comment by toystars** [comment]
@Adar-Li will do and get back at you ASAP
