### ISSUE TITLE
Focus probs iOS

### ISSUE THREAD

**Issue by izzyreal** [toystars/react-native-multiple-select#117]
Anyone else noticed a problem with focus on iOS? I'm trying this component's example on iPhone 11 Pro Max 13.0 emulator.

When opening the dropdown, I first have to give the actual list of items focus by tapping on it, before I'm able to select any of the items. Then when I want to search by typing, I have to give the TextInput focus by tapping on that.

I would like the list of items and the TextInput to accept taps simultaneously, while any keyboard input is automatically directed to the TextInput.

**Comment by dejavu20180307** [comment]
probably because textInput is autoFocus in code. This is annoying, user has to click twice to change selection.

**Comment by cekali** [comment]
Try setting: 

`textInputProps={{ autoFocus: false }}`

**Comment by izzyreal** [comment]
I'm not using this component anymore, so I can't try your suggestion. As far as I'm concerned this ticket can be closed.
