### ISSUE TITLE
List of items not being updated once a new item is added

### ISSUE THREAD

**Issue by andrebr** [toystars/react-native-multiple-select#13]
The `MultiSelect` component isn't showing items added after the first render.

```
constructor(props) {
  super(props);

  this.state = {
    items: [{id: 1, name: 'A'}]
  }
}
```

```
<MultiSelect
  items={this.state.items}
  ...
/>
```

List shows item 'A' as expected. but once we add 'B' to the list, it's not showing the new item on the list:

```
const items = this.state.items;
items.push({ id: 2, name: 'B' });

this.setState({ items });
```

List still shows 'A', while we expect to see 'A' and 'B'.

Same thing happens to `selectedItems`.

Would be great to be able to update both lists once we set the new state.

Thanks for the awesome component!

**Comment by Matroskinb** [comment]
`componentWillReceiveProps(nextProps) {
    this.setState({ items: nextProps.items });
  }`

add this to component code

**Comment by sam9010** [comment]
can i sample code of that?
