### ISSUE TITLE
Android: fixedHeight makes last dropdown list elements unclickable

### ISSUE THREAD

**Issue by ASchwad** [toystars/react-native-multiple-select#136]
## Issue summary
fixedHeight seems buggy under Android. The last elements of the selection cannot be selected. There is no following component which "overlays" the selection. Is there a fix for this problem? Only occurs on Android, iOS works nicely. In the gif, i tried tapping the elements at the end of the list, after scrolling up, i can click them. The last 1-3 elements are always unclickable...

I tried upping the z-Index and adding a fixed height styling property but without success.

![Mar-05-2020 11-35-42](https://user-images.githubusercontent.com/33654656/75973638-cab31380-5ed5-11ea-9377-f19a6c142203.gif)

### Steps to Reproduce

(Write your steps here:)

1. Use sample app from readme
2. Add fixedHeight = {true}
3. Have more than 10 elements in your list

### Expected Behavior
All items should be clickable

(Write what you thought would happen.)

### Actual Behavior
Last items are non-clickable

**Comment by michelegoh** [comment]
Adding `flatListProps={{contentContainerStyle: {paddingBottom: 30}}}` for whatever value of `paddingBottom` suits you solves the problem of not being able to click on the bottom elements, but it does also add blank space at the end of the list.

**Comment by ASchwad** [comment]
Thanks for your input. This fixes the problem only partially. I can scroll the list up enough to click also the last elements. 
The essence of the problems lays within the lower part of the MultiSelect not reacting to clicks. 
e.g. the select button can still not be clicked with your fix.

**Comment by ASchwad** [comment]
You have brought me into the right direction! I deleted the `fixedHeight = {true}` property and added `flatListProps={{height: 200}}`. Thank you.
