### ISSUE TITLE
Unable to change the background color

### ISSUE THREAD

**Issue by cullsin** [toystars/react-native-multiple-select#139]
## Issue summary

![image](https://user-images.githubusercontent.com/5137598/81503741-e1754c80-9302-11ea-8a5c-c2bc5faf12c8.png)

### Library versions

   "react-native": "0.61.5"
  "react-native-multiple-select": "^0.5.5",

### Steps to Reproduce

(Write your steps here:)

Unable to change the background color, font, and other property.

### Expected Behavior

Suppose to have an option to change it.

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Code

(Paste exact code snippet and instructions to reproduce the issue.)

**Comment by cbpatel93** [comment]
![Screenshot_1589873908](https://user-images.githubusercontent.com/54405792/82298547-e8baeb00-99d1-11ea-81f2-5a120e03dd54.png)
same issue

**Comment by musadiq-jinbade** [comment]
@cbpatel93  any update on this?

**Comment by sanderlandsmeer** [comment]
I was able to use `styleDropdownMenuSubsection={{ backgroundColor: 'transparent' }}`. I am using version 0.5.5. Doesn't that work for you?

**Comment by Gugan-raj** [comment]
styleDropdownMenuSubsection={{ backgroundColor: 'transparent' }}
its works for me

**Comment by rajusiripalli** [comment]
> styleDropdownMenuSubsection={{ backgroundColor: 'transparent' }}

thank you so much me it's working
