### ISSUE TITLE
This component has heavy dependencies

### ISSUE THREAD

**Issue by jayesbe** [toystars/react-native-multiple-select#14]
I need to install native-base along with the entirety of underscore.. isn't that a bit much?

This seems to be more of a component built specifically for native-base and not just react-native ?

**Comment by toystars** [comment]
Removing dependency on native-base as been on the pipeline. It will be done in the next release. Also about underscore, that will also be cleaned up.

**Comment by cerberusv2px** [comment]
When will the next release come? Because I had to remove all the native-base component in the library and add the react native components. Still having some UI problem but works.

**Comment by toystars** [comment]
@cerberusv2px the new release is available now with all heavy dependencies removed. Native base has been removed completely and underscore replaced with lodash with functions picking.

**Comment by cerberusv2px** [comment]
@toystars I have made some changes in your library while implementing in my project. I think mine one is more user friendly(No offense). Would you like to take a look at it? UI are still not perfect but just made how i wanted to using your components.

**Comment by toystars** [comment]
@cerberusv2px sure, I'll like to take a look at it. Can you create a fork and push to that? Then I can try it out from there.

**Comment by cerberusv2px** [comment]
@toystars Here is the link
https://github.com/cerberusv2px/react-native-multiple-select/blob/master/lib/react-native-multi-select.js

You can try this out. Its still not perfect in terms of UI. And i think i may have removed the single selection of the items. Can you please take a look at it and let me know. There might still be some bugs. It was difficult for me to understand the logic behind the library.
