### ISSUE TITLE
Android fixHeight error with parent ScrollView

### ISSUE THREAD

**Issue by cerberusv2px** [toystars/react-native-multiple-select#17]
The fixHeight doesnot work on andorid when there is parent scrollView present.
The whole component scrolls instead of just the data. This is problem only on android devices and works fine for iOS devices.
How to solve this problem?

**Comment by cerberusv2px** [comment]
I solved this problem by removing the fixHeight props and only showed the list of data when user types more than 2 letters.

**Comment by SushilShrestha** [comment]
Same error. Looks like ScrollView Implementation has some flaws. 
https://github.com/facebook/react-native/issues/1966
