### ISSUE TITLE
How to use MultiSelect inside ScrollView?

### ISSUE THREAD

**Issue by matpiwowarski** [toystars/react-native-multiple-select#175]
## Issue summary
I'm using MultiSelect inside ScrollView but I'm getting warning "VirtualizedLists should never be nested inside plain ScrollViews with the same orientation". 

### How can I get rid of this warning?

**Comment by matpiwowarski** [comment]
https://www.npmjs.com/package/react-native-select-multiple

**Comment by ahmetgsu** [comment]
Using `FlatList` instead of `ScrollView` solved this issue for me.

**Comment by antoniofacciutiIYL** [comment]
I used a workaround to bypass this problem hiding the search input and add "fixedHeight" to true
` <MultiSelect
            items={Categories}
            uniqueKey="id"
            onSelectedItemsChange={onSelectedItemsChange}
            selectedItems={entry.categories}
            fixedHeight={true}
            hideSubmitButton={true}
            hideTags={true}
            styleInputGroup={{ display: "none", }}
            hideDropdown={true}
          />`

**Comment by sahijoshi** [comment]
import {ScrollView} from 'react-native-virtualized-view'

This worked for me.
