### ISSUE TITLE
Multiple select in ScrollView

### ISSUE THREAD

**Issue by amirbhz86** [toystars/react-native-multiple-select#199]
I am using this library in Scrollview 
and I always facing this error in ios devices

![WhatsApp Image 2022-03-15 at 6 11 00 AM](https://user-images.githubusercontent.com/76239413/158335338-476484d8-67af-45d0-8a6d-905a68076ecd.jpeg)
e

I saw this issue and it seems nobody has a fix for it
https://github.com/toystars/react-native-multiple-select/issues/175

**Comment by amirbhz86** [comment]
I found a solution after some time
just import ScrollView from react-native-virtualized-view

like this : 
```
import { ScrollView } from 'react-native-virtualized-view'
```

**Comment by AugustoAleGon** [comment]
Thanks for the solution.
