### ISSUE TITLE
multiselect in ScrollViews gives error

### ISSUE THREAD

**Issue by benohiit** [toystars/react-native-multiple-select#207]
## Issue summary
I have the Error:
VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.

But it's actually working fine. How can I get rid of this warning/error please ?

### Library versions  
  react-native: 0.68.1
  react-native-multiple-select: 0.5.11

**Comment by AugustoAleGon** [comment]
This is not an issue related to the library. 
I am gonna close this issue.
If you wanna get rid of the warning just check [https://stackoverflow.com/questions/58243680/react-native-another-virtualizedlist-backed-container](link).
