### ISSUE TITLE
How to remove search icon?

### ISSUE THREAD

**Issue by bogannathan** [toystars/react-native-multiple-select#40]
Sorry if this is elsewhere. We don't want the search icon (or the search feature) at all. Is there a way to remove it?

Thanks!

**Comment by toystars** [comment]
Removing search is not possible as at now. Should be added later on. PR is also welcome

**Comment by raphcadiz** [comment]
Did someone able to add this feature to be able to disable search

**Comment by fareedMurad** [comment]
add prop like this searchIcon={null}
