### ISSUE TITLE
getSelectedItemsExt Undefined

### ISSUE THREAD

**Issue by AlfaIrawan** [toystars/react-native-multiple-select#58]
Hey @toystars , I also have this issue. Do you have any Idea?

<img width="321" alt="screen shot 2018-02-08 at 21 46 30" src="https://user-images.githubusercontent.com/6032283/35978998-b954a208-0d19-11e8-803f-b0d7c0137c18.png">

**Comment by toystars** [comment]
This happens because the method is being called before the component reference has been set. You can do something like this:

```
{
   this.multiselect
    ? 
   this.multiselect.getSelectedItemsExt()
    :
    null
}
```

This checks that the component reference has been set before invoking the method. The snippet above assumes that the ref is stored in `this.multiselect`

**Comment by AlfaIrawan** [comment]
Thx u @toystars you solve my problem

**Comment by GabrielGoncalvesSottelli** [comment]
Hey @toystars, I'm trying to make the selected items appear but I'm not getting it.

Do you know what I might be doing wrong?

`// import component
import React, { Component } from 'react';
import { View } from 'react-native';
import MultiSelect from 'react-native-multiple-select';

export default class SelectOptionsMultipleTester extends React.PureComponent {
    constructor(props) {
        super(props);
        this.state = {
            selectedItems: []
        };
    }

    render() {
        const items = [{
            id: '92iijs7yta',
            name: 'Ondo',
        }, {
            id: 'a0s0a8ssbsd',
            name: 'Ogun',
        }, {
            id: '16hbajsabsd',
            name: 'Calabar',
        }, {
            id: 'nahs75a5sg',
            name: 'Lagos',
        }, {
            id: '667atsas',
            name: 'Maiduguri',
        }, {
            id: 'hsyasajs',
            name: 'Anambra',
        }, {
            id: 'djsjudksjd',
            name: 'Benue',
        }, {
            id: 'sdhyaysdj',
            name: 'Kaduna',
        }, {
            id: 'suudydjsjd',
            name: 'Abuja',
        }];

        const onSelectedItemsChange = selectedItems => {
            this.setState({ selectedItems });
        };
     
        const { selectedItems } = this.state;   
        
        return(
            <View style={{ flex: 1 }}>
                <MultiSelect
                    hideTags
                    items={items}
                    uniqueKey="id"
                    ref={(component) => { this.multiSelect = component }}
                    onSelectedItemsChange={onSelectedItemsChange}
                    selectedItems={selectedItems}
                    selectText="Selecionar itens"
                    searchInputPlaceholderText="Procurar itens..."
                    onChangeInput={ (text)=> console.log(text)}
                    altFontFamily="ProximaNova-Light"
                    tagRemoveIconColor="#CCC"
                    tagBorderColor="#CCC"
                    tagTextColor="#CCC"
                    selectedItemTextColor="#CCC"
                    selectedItemIconColor="#CCC"
                    itemTextColor="#000"
                    displayKey="name"
                    searchInputStyle={{ color: '#CCC' }}
                    submitButtonColor="#CCC"
                    submitButtonText="Selecionar"
                />
                <View>
                    {
                        this.multiselect
                            ? 
                        this.multiSelect.getSelectedItemsExt(selectedItems)
                            :
                        null
                    }
                </View>
            </View>
        );
    }
}`

Thanks in advance :)

**Comment by ranu-patidar** [comment]
how to create reference fot open other button in react-native-multiple-select

**Comment by AugustoAleGon** [comment]
@ranu-patidar What are you trying to achieve?
