### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by murilomothsin** [toystars/react-native-multiple-select#6]
Hi I'm having an error when run babelify.

This is the command:

`browserify -t [ babelify --presets [ es2015 es2016 react ] ] app/main.js -o app/bundle.js
`

and this is the error:

```
/my-project/node_modules/react-native-multiple-select/index.js:6
import MultiSelect from './lib/react-native-multi-select';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Can someone help me?

**Comment by toystars** [comment]
@murilomothsin I think you are using the package in a `react` app, yeah? The package is meant to be used in `react-native` apps.

**Comment by murilomothsin** [comment]
Oh, I'm sorry. My mistake ahahah

Thanks :smile:
