### ISSUE TITLE
Move react, react-native and react-native-vector-icons to peerDependencies

### ISSUE THREAD

**Issue by asquet** [toystars/react-native-multiple-select#7]
`package.json` states requirements for specific versions of these libs. I already use more recent versions, so my app crashes on build because of conflicting `react-native-vector-icons`.
I think updating and moving these dependencies to peerDependencies could help

**Comment by toystars** [comment]
@asquet thanks for the heads-up. Will replicate and do the needful.

**Comment by raoulj** [comment]
+1

**Comment by toystars** [comment]
This should be fixed with this #8
