### ISSUE TITLE
How do I decrease the width of the items that have been selected? Thanks

### ISSUE THREAD

**Issue by Evymendes** [toystars/react-native-multiple-select#92]
How do I decrease the width of the items that have been selected?

**Comment by AugustoAleGon** [comment]
Well. First the update version comes from Github. So you must add like this: `yarn add https://github.com/toystars/react-native-multiple-select`.
Then there is a property called `styleRowList` when you can change the width of the item, but right now for selected items there is not a different styles. But if you want to add it. PR are always welcome.
