### ISSUE TITLE
Android | how to add extra style for entire multiselect text box

### ISSUE THREAD

**Issue by LudinaReema** [toystars/react-native-multiple-select#94]
## Issue summary
Add a short description of issue, preferably, a sentence.

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Code

(Paste exact code snippet and instructions to reproduce the issue.)

**Comment by LudinaReema** [comment]
- Border radius,
- Background color

**Comment by AugustoAleGon** [comment]
What are the text box that you are referring to? There are two main views. One of then is when you haven't clicked on the text box and the other one is after.

**Comment by SkyTreasure** [comment]
The outer text box before clicking.

**Comment by tylerolechnowicz** [comment]
I would also like help with this! I am trying to figure out how to move the text over to the right so it's not up against the edge. I would greatly appreciate the help!

![image](https://user-images.githubusercontent.com/32344917/61757975-d1e74000-ad90-11e9-9650-3e937bba9230.png)

**Comment by dpk89** [comment]
@tylerolechnowicz You can use this props styleDropdownMenuSubsection it will allow you to  style the inner section of the  main component
SOMETHING LIKE THIS 
   styleDropdownMenuSubsection={{
          paddingLeft: 5,
        }}

**Comment by AugustoAleGon** [comment]
@dpk89 correct that's the solution
