### ISSUE TITLE
Styling Does Not Work

### ISSUE THREAD

**Issue by tylerolechnowicz** [toystars/react-native-multiple-select#96]
## Issue summary
The stylings for the multiple select dropdown component do not seem to be working. I am trying to get the initial text of the dropdown moved over to the right a little bit because it is right on the edge of the left side.

### Library versions

  react-native: 0.57.1
  react-native-multiple-select: 0.4.4

### Steps to Reproduce

Try any of the stylings...They do not seem to be doing anything other than 'searchInputStyle'.

### Expected Behavior

I expected to be able to have more control over the styling of the dropdown menu.

### Actual Behavior

I basically have no control over the styling of the dropdown menu. I can't move the initial drop down text over to the right and I can't adjust the height of the dropdown list when using the 'fixedHeight' prop. I would like to adjust the height of 'fixedHeight', as of right now it creates an awkward gap if the list does not fill the height.

![image](https://user-images.githubusercontent.com/32344917/55564214-66844000-56c5-11e9-98a0-8245b28368be.png)

**Comment by AugustoAleGon** [comment]
Try with this: https://github.com/toystars/react-native-multiple-select.git instead with version.

**Comment by tylerolechnowicz** [comment]
AugustoAleGon,

That is the version that I am currently using. Isn't 0.4.4 the latest?

**Comment by AugustoAleGon** [comment]
@tylerolechnowicz no unfortunately I don't have permissions to upload via npm the latest version. So in the meantime try `yarn add https://github.com/toystars/react-native-multiple-select`

**Comment by tylerolechnowicz** [comment]
Sorry AugustoAleGon,

I guess I am not fully understanding...but what is the latest version of https://github.com/toystars/react-native-multiple-select? I believe that I already have the latest version installed...

**Comment by toystars** [comment]
@AugustoAleGon apologies for that. I'm having issues with 2FA I set up on npm and I can't add new collaborators yet. Once I resolve this, I'll add you up.

**Comment by AugustoAleGon** [comment]
@tylerolechnowicz  the only way to get the lastest is the way I mentioned before. Via Npm you won't get the lastest version.

**Comment by tylerolechnowicz** [comment]
@AugustoAleGon do you know when the latest version will be available via npm? My project is made with expo and yarn is causing a bunch of issues.

**Comment by AugustoAleGon** [comment]
@tylerolechnowicz I am really sorry about that issue. I already sent an email from @toystars . Let's wait for it.

**Comment by tylerolechnowicz** [comment]
@AugustoAleGon @toystars thank you both. I am very excited to start using this package to its fullest.

**Comment by toystars** [comment]
@AugustoAleGon please can you send me your npm username so I can add you up? I just resolved the issues with my 2FA. Thanks.

**Comment by AugustoAleGon** [comment]
@toystars my username is the same. Let me know if you need something else.

**Comment by toystars** [comment]
@AugustoAleGon I keep getting user not found on npm.

**Comment by AugustoAleGon** [comment]
@tylerolechnowicz  I am gonna close this issue. The npm package was published today.
