### ISSUE TITLE
Disable auto-focus on search input

### ISSUE THREAD

**Issue by co-de** [toystars/react-native-multiple-select#98]
Hello. First of all, I appreciate the work you have done so far. Work beautifully. I have a small problem though. When I toggle the list visible, it auto-focuses on the search box and this brings up the phone's keyboard up automatically. Can I disable this auto-focus?

**Comment by co-de** [comment]
Ok I got this. https://github.com/toystars/react-native-multiple-select/blob/51b97b710aca4565c7da0a8a60111e34492de93a/lib/react-native-multi-select.js#L540

Just commented out this line and it is done.

**Comment by AugustoAleGon** [comment]
Actually you can pass props and do something like `autoFocus={false}`

**Comment by 1442916418** [comment]
thank you!

**Comment by mo-patel** [comment]
Hi, passing `autoFocus={false}` to the multi-select does not work for me. Am i missing something or is the only way to solve this by removing `autofocus` from the file?

**Comment by AugustoAleGon** [comment]
@mo-patel  are passing and object on the property `textInputProps`? Like this:
```
textInputProp = {
    autoFocus = {false}
}
```

**Comment by mo-patel** [comment]
@AugustoAleGon Ah, my bad, i completely missed the textInputProp option. It works fine now, thank you very much.

**Comment by AugustoAleGon** [comment]
@mo-patel No worries.

**Comment by serge-jerkezian** [comment]
this worked for me 

`textInputProps={{autoFocus:false}}`
