### ISSUE TITLE
2 seperate arrows displayed when the submit button is disabled

### ISSUE THREAD

**Issue by co-de** [toystars/react-native-multiple-select#99]
When I use hideSubmitButton parameter, I start seeing 2 arrows next to each other inside the searchbox. How can I avoid this?

Thanks a lot for all the effort!

![SmartSelect_20190508-173340](https://user-images.githubusercontent.com/13452081/57384322-0e0afb80-71b9-11e9-906f-91d70394c692.jpg)

**Comment by co-de** [comment]
I found the line in the code and removed the extra arrow on the right. Can be closed.

**Comment by michaelVictoriaDev** [comment]
how ? @co-de

**Comment by erickgtzh** [comment]
There's a way to do it using styles??
